// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WPF_menza_projekt.models;

#nullable disable

namespace WPF_menza_projekt.Migrations
{
    [DbContext(typeof(menza))]
    [Migration("20260320131256_harmadik")]
    partial class harmadik
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WPF_menza_projekt.models.desszert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("desszertek");
                });

            modelBuilder.Entity("WPF_menza_projekt.models.foetel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("foetelek");
                });

            modelBuilder.Entity("WPF_menza_projekt.models.leves", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("levesek");
                });

            modelBuilder.Entity("WPF_menza_projekt.models.napietkezes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("datum")
                        .HasColumnType("date");

                    b.Property<int?>("desszertid")
                        .HasColumnType("int");

                    b.Property<int>("foetelid")
                        .HasColumnType("int");

                    b.Property<int>("levesid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("desszertid");

                    b.HasIndex("foetelid");

                    b.HasIndex("levesid");

                    b.ToTable("napietkezesek");
                });

            modelBuilder.Entity("WPF_menza_projekt.models.vendeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("diak")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("nev")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("vendegek");
                });

            modelBuilder.Entity("WPF_menza_projekt.models.vendegnapietkezes", b =>
                {
                    b.Property<int>("vendegid")
                        .HasColumnType("int");

                    b.Property<int>("napietkezesid")
                        .HasColumnType("int");

                    b.HasKey("vendegid", "napietkezesid");

                    b.HasIndex("napietkezesid");

                    b.ToTable("vendegnapietkezesek");
                });

            modelBuilder.Entity("WPF_menza_projekt.models.napietkezes", b =>
                {
                    b.HasOne("WPF_menza_projekt.models.desszert", "desszert")
                        .WithMany()
                        .HasForeignKey("desszertid");

                    b.HasOne("WPF_menza_projekt.models.foetel", "foetel")
                        .WithMany()
                        .HasForeignKey("foetelid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WPF_menza_projekt.models.leves", "leves")
                        .WithMany()
                        .HasForeignKey("levesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("desszert");

                    b.Navigation("foetel");

                    b.Navigation("leves");
                });

            modelBuilder.Entity("WPF_menza_projekt.models.vendegnapietkezes", b =>
                {
                    b.HasOne("WPF_menza_projekt.models.napietkezes", "napietkezes")
                        .WithMany()
                        .HasForeignKey("napietkezesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WPF_menza_projekt.models.vendeg", "vendeg")
                        .WithMany()
                        .HasForeignKey("vendegid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("napietkezes");

                    b.Navigation("vendeg");
                });
#pragma warning restore 612, 618
        }
    }
}
